### ISSUE TITLE
Local Connect: How to get encryption key?

### ISSUE THREAD

**Issue by Niwla23** [fsantini/python-e3dc#10]
How do I get my encryption key? Cant find it on the display. Is it in the web interface? @fsantini

**Comment by fsantini** [comment]
You can set it yourself through the touch interface in the preferences. If you still cannot find it I will check tonight on my system and come back to you with the exact directions.

**Comment by Niwla23** [comment]
Maybe its RSCP Password?
I found RSCP Password and RSCP local user password, so I think RSCP is the encrption key?

**Comment by fsantini** [comment]
Yes it should be that

**Comment by Niwla23** [comment]
Thanks, I will try when my father allows it :+1:
