### ISSUE TITLE
Getting history data

### ISSUE THREAD

**Issue by steff333** [fsantini/python-e3dc#18]
Im trying to read the history data with DB_REQ_HISTORY_DATA_DAY but can't get it to work.
The reason is to get the daily sums for production, grid etc.

Did you get it to work?
I checked for example  
e3dc.sendRequest(('DB_REQ_HISTORY_DATA_DAY', 'Container', [
        ('DB_REQ_HISTORY_TIME_START', 'Uint16', 0),
        ('DB_SUM_CONTAINER', 'None', None),]), keepAlive=True)
but always only get errors back.

Can you help?

**Comment by fsantini** [comment]
I can try, but it seems that it's an error in the format of the request, and I have no clue about those. I only know how to handle the low-level communication. How did you come up with this request?

**Comment by steff333** [comment]
Honestly, I tried to get access to the archive values - I'm missing a proper documentation from e3dc.
Is there a better way to retrieve e.g. the total amount of production by day?

It would be rather dull to read the data every second and calculate something manually.

Am 24. Mai 2020 22:03:32 MESZ schrieb fsantini <notifications@github.com>:

**Comment by steff333** [comment]
I think I fixed it and sent you a pull request for the python3 branch

**Comment by vchrisb** [comment]
Thank you very much for your contribution. #20 
I already picked up your enhancements for [e3dc-rest](https://github.com/vchrisb/e3dc-rest).
