### ISSUE TITLE
publish via pypi

### ISSUE THREAD

**Issue by vchrisb** [fsantini/python-e3dc#29]
It would be great to distribute python-e3dc via pypi.

The name `e3dc` is already taken by an old fork based on `python-e3dc`: `https://pypi.org/project/e3dc/`

Any suggestion on the naming? 

required tasks (need to be updated): 

- [ ] establish versioning and release management
- [ ] build and deploy pipeline

**Comment by fsantini** [comment]
Yes that would be good. I think that the project is mature enough for that.

We could call it PyE3DC.
