### ISSUE TITLE
Is it compatible with python3?

### ISSUE THREAD

**Issue by Niwla23** [fsantini/python-e3dc#3]
if not, please make it compatible as python will drop the 2.x.x series in the near future

**Comment by fsantini** [comment]
Hi good remark, I've been postponing it for too long. I'll work on it. Fortunately the rijndael algorithm is now available in PyPI so it should be easier. There is still quite a lot of string/byte stuff though that could be nasty.

**Comment by fsantini** [comment]
I think it's working now, please check the python3 branch. It now depends on py3rijndael available on PyPI (the crypto library is no more included)
