### ISSUE TITLE
PytzUsageWarning

### ISSUE THREAD

**Issue by kkro** [fsantini/python-e3dc#45]
python 3.9 on Windows 11 all updated to newest 08.11.2021

e3dc_rscp_web.py:54: 
PytzUsageWarning: 
The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

This helps:
--    localNow = localtz.localize(naiveNow)
++    localNow = naiveNow

**Comment by vchrisb** [comment]
Thank you.
`localNow` in 
https://github.com/fsantini/python-e3dc/blob/8580661ab3d76b410fe573d65f2fcc8276c11091/e3dc/_e3dc_rscp_web.py#L54
and
https://github.com/fsantini/python-e3dc/blob/8580661ab3d76b410fe573d65f2fcc8276c11091/e3dc/_e3dc_rscp.py#L54
actually even aren't used! I'm going to remove these artifacts.
