### ISSUE TITLE
Python 2.7 EOL

### ISSUE THREAD

**Issue by vchrisb** [fsantini/python-e3dc#5]
With Python 2.7 having reached its end of life, any plans to update to Python 3? 
Thank you!

**Comment by fsantini** [comment]
Yes, please check the python3 branch: https://github.com/fsantini/python-e3dc/tree/python3

It's ported but not thoroughly tested, it would help me a lot if you could give it a try!

**Comment by vchrisb** [comment]
Cool, I'll give it a try!
