### ISSUE TITLE
get_power_data throws TypeError

### ISSUE THREAD

**Issue by mdhom** [fsantini/python-e3dc#51]
First of all: MANY THANKS for this great library which made it easy to fetch data from my E3/DC system.
I get the poll data working, now i wanted to fetch the power data:
```
power_data = e3dc.get_power_data()
print(power_data)
```
But it throws an error:
` <class 'TypeError'> 'NoneType' object is not subscriptable`

I guess that `rscpFindTag` returns None here:
https://github.com/fsantini/python-e3dc/blob/1b5bb8013f08bcec4d6b3ccb7160c161755f9c23/e3dc/_e3dc.py#L956

Question is: why can't it find the tags in my system?
Am i doing something wrong here?

Thanks,
Max

**Comment by mdhom** [comment]
I printed the result of the `sendRequest` call and received this:
```
('PM_DATA', 'Container', [('PM_INDEX', 'Uint16', 0), ('PM_DEVICE_STATE', 'Error', 'RSCP_ERR_NOT_AVAILABLE')])
```

**Comment by mdhom** [comment]
Could you give me a link or something where that RSCP protocol is documented? I can't find anything around the internet but would be very willing to contribute here.

**Comment by vchrisb** [comment]
what E3DC Model do you have?
Sadly there isn't much documentation available from E3DC.  In the download section of the E3DC portal is only some documentation from 2016...

**Comment by mdhom** [comment]
E3/DC S10E Pro is my model

**Comment by mdhom** [comment]
> what E3DC Model do you have? Sadly there isn't much documentation available from E3DC. In the download section of the E3DC portal is only some documentation from 2016...

Ah, found those two documents. But where did you get tags like `PM_REQ_POWER_L1` from? Can't find that anywhere in these pdfs...

**Comment by vchrisb** [comment]
Reverse engineering and try and error. The portal is also using rscp and has a list of all tags. https://s10.e3dc.com/s10/js/rscpLibV0.9.2.min.js

**Comment by vchrisb** [comment]
You can try a different value for `pmIndex` https://github.com/fsantini/python-e3dc/blob/master/e3dc/_e3dc.py#L140. Not sure if someone else validated if `pmIndex = 0` is correct for a S10 Pro.
@fsantini has a S10E and I have a S10mini. So these are the products we test against.

**Comment by mdhom** [comment]
@vchrisb, @fsantini added pull request that fixes the pmIndex for S10 Pro, tested it with my system here!
