### ISSUE TITLE
Read multiple powermeter

### ISSUE THREAD

**Issue by maaque** [fsantini/python-e3dc#61]
I have 2 power meter installed. How do I read the status of each of them? I do not find the correct tags in _rscptags.

**Comment by vchrisb** [comment]
`get_powermeter_data` does allow passing an index of your powermeters: https://github.com/fsantini/python-e3dc/blob/master/e3dc/_e3dc.py#L1723
You will need to try out which are the correct indexes in your configuration.
`0` and `6` are root powermeter, and other indexes will be additional meters.
Once you know the indexes in your configuration, you can optionally initialize the package with this information:
```
{
  "powermeters": [
    {
      "index": 0
    },
    {
      "index": 3
    }
  ]
}
```

and also optionally use `get_powermeters_data ` to query both in one go.
