### ISSUE TITLE
Web connection always fails with KeyError: 'PM0_L1'

### ISSUE THREAD

**Issue by t11z** [fsantini/python-e3dc#64]
Hi,

it seems as if E3DC has changed their power meter index starting at 1 and not at 0 anymore.

When doing a simple

```
e3dc = E3DC(E3DC.CONNECT_WEB, username=USERNAME, password=PASS, serialNumber = SERIALNUMBER, isPasswordMd5=False)
print(e3dc.poll())
print(e3dc.poll_switches())
```

script execution always fails with

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    print(e3dc.poll())
  File "/home/satoshi/.local/lib/python3.8/site-packages/e3dc/_e3dc.py", line 310, in poll_ajax
    int(raw["PM" + strPmIndex + "_L1"])
KeyError: 'PM0_L1
```

In the `raw` variable output I could see that index seems to have changed:

```
{
[...]
'PM1_L1': '0',
'PM1_L2': '0',
'PM1_L3': '0',
'PM2_L1': '0',
'PM2_L2': '0',
'PM2_L3': '0',
'PM3_L1': '0',
'PM3_L2': '0',
'PM3_L3': '0',
'PM4_L1': '0',
'PM4_L2': '0',
'PM4_L3': '0',
[...]
}
```

With a simple change in __e3dc.py_ I could fix it:

before (line 146):

`self.pmIndexExt = 0`

after (line 146):

`self.pmIndexExt = 1`

I have got an S10 mini installed in 2019. Can other people confirm the same for other types of installations?

**Comment by vchrisb** [comment]
fixed by #65
