### ISSUE TITLE
Inconsistent floating-point precision for battery and DCB values

### ISSUE THREAD

**Issue by eikowagenknecht** [fsantini/python-e3dc#91]
There is a inconsistency between the floating-point precision in the battery and DCB current values.

While investigating issue #86, I noticed that the `current` field in the battery object is rounded to two decimal places:

```python
"current": round(rscpFindTagIndex(req, RscpTag.BAT_CURRENT), 2),
```

However, in the DCB object, it's not:

```python
"current": rscpFindTagIndex(info, RscpTag.BAT_DCB_CURRENT),
```

This also is relevant for the other fields in the battery object.

To standardize this, I propose using unrounded values for both. This is beneficial for situations where the caller may need to change the unit (e.g., W to kW) or perform additional calculations that require greater precision.

**Comment by vchrisb** [comment]
I like things to be consistent and fine with not rounding. 💯
